# Generated by Django 3.0.6 on 2020-06-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200613_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='path',
            new_name='src',
        ),
        migrations.AddField(
            model_name='photo',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
