# Generated by Django 3.1.2 on 2020-10-27 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.', regex='^[\\w.@+\\-]+$'), django.core.validators.MinLengthValidator(3, message='Enter a valid username. This value should be between 3 and 25 characters long.')]),
        ),
    ]
