# Generated by Django 3.1.2 on 2020-10-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200819_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='src',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
