# Generated by Django 3.1.2 on 2020-10-04 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201004_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='src',
            new_name='image',
        ),
    ]
