# Generated by Django 3.1.2 on 2020-10-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201010_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
