# Generated by Django 3.1.2 on 2020-10-26 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_photo_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid project name. This value may only contain letters, numbers or one of the following characters: @, -, _', regex='^[\\w.@+\\-]+$')]),
        ),
    ]
