# Generated by Django 3.1.2 on 2020-11-11 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201026_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='hash',
        ),
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(blank=True, max_length=256, null=True)),
                ('is_duplicated', models.BooleanField(default=False)),
                ('duplicate_id', models.IntegerField(default=None, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'no_duplicate'), (1, 'todo'), (2, 'done'), (3, 'skipped')], default=0)),
                ('date_status', models.DateTimeField(auto_now_add=True, null=True)),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.photo')),
            ],
            options={
                'ordering': ['status', '-date_status'],
            },
        ),
    ]
