# Generated by Django 3.1.2 on 2020-11-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201111_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hash',
            name='duplicate_id',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
