# Generated by Django 3.1.2 on 2020-11-17 23:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201117_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hash',
            name='date_status',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
