# Generated by Django 3.1.3 on 2020-12-16 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201117_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hash',
            options={'ordering': ['-status', '-date_status']},
        ),
    ]
