# Generated by Django 3.1.3 on 2020-12-23 16:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20201223_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='exif',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
