# Generated by Django 3.1.3 on 2020-12-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_photo_exif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='exif',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
