# Generated by Django 3.1.3 on 2020-12-25 17:08

from django.db import migrations, models
import piclab.api.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20201223_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=piclab.api.models.upload_path_thumbnail),
        ),
    ]
