name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Backend
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      working-directory: ./backend
      run: |
        ls -la
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
    - name: Set environment variables
      working-directory: ./backend
      run: |
        echo "SECRET_KEY=$(pipenv run python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())')" >> $GITHUB_ENV
    - name: Run test suite
      working-directory: ./backend
      run: |
        pipenv run python manage.py test

    # Frontend
    - name: Setup Node.js
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 13.x
    - name: Install dependencies
      working-directory: ./frontend
      run: npm install
    - name: Build app
      working-directory: ./frontend
      run: npm run build
